name: Lint and Format Check

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
    
permissions:
  contents: write 
  
jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # or your project's Node version

      - name: Install dependencies
        working-directory: my-app
        run: npm install

      - name: Run linter
        working-directory: my-app
        run: npm run lint

      - name: Run build
        working-directory: my-app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: my-app/dist
          clean: true
